# Generated by Django 3.0.4 on 2020-05-20 15:09
from __future__ import unicode_literals

from django.db import migrations, models
from datetime import datetime
from django.conf import settings
from room_reserve.models import *

roles   = ['superuser','admin','client']

def create_role(apps,schema_editor):
    for obj in roles:
        RoleModel.objects.create(title=obj)


def create_superuser(apps, schema_editor):
    UserModel.objects.create_superuser(username='admin',
                                       password='adminadmin',
                                       verification_code='adminadmin',
                                       email=settings.EMAIL_HOST_USER)


class Migration(migrations.Migration):

    dependencies = [
        ('room_reserve', '0001_initial'),
    ]

    operations = [
        
        migrations.RunPython(create_role),
        migrations.RunPython(create_superuser),
    ]
